### PR TITLE
Add support to scan directories

### PR DESCRIPTION
**Pull request by pierredup**
Add support to scan directories

### CODE REVIEW

**Comment by hikari-no-yume** [comment]
I don't like this. There's no good reason to make scan() take a filename.

**Comment by pierredup** [comment]
I only added the filename to `scan()` so that it can be passed to the `Scanner` class, in order to display the filename in the output.

Originally I didn't have the filename in the scan() function, but figured it would be better for compatibility if you want to scan through directories

**Comment by hikari-no-yume** [comment]
We didn't do this before and were able to display the filename in the output. There's no need to do it now, it makes unit testing more difficult.

**Comment by pierredup** [comment]
The filename was part of the output originally, because you could only pass in file names for the arguments. When scanning a directory, you can't use the argument any more, because it will only show the name of the directory you scanned, and not the file where match was found.

**Comment by pierredup** [comment]
Okay I've refactored the code a bit to remove the file from the scan() function

**Comment by hikari-no-yume** [comment]
Alright, I'm fine with that. One possibility, though: perhaps, instead of implicitly scanning directories, it should be an option, like `-r` for recursive? Consider that you might not want to go into subdirectories. Perhaps it should skip directories unless `-r` is given?

**Pull request closed without merging**
